---

- name: Ensure git is installed
  apt: name=git state=present
  become: true

- name: Ensure directory is there
  file:
    dest: "{{ item }}"
    state: directory
  become: true
  become_user: "{{ user }}"
  with_items:
    - "{{ service_dir }}"
    - "{{ go_path }}/src/github.com/tools/godep"

- name: Clone service repo
  git:
    repo="https://github.com/Tinker-Ware/{{ item.name }}.git"
    dest="{{ service_dir }}/{{ item.name }}"
    update=yes
    force=yes
  become: true
  become_user: "{{ user }}"
  with_items: "{{ services }}"
  tags:
    - update_custom_service_repo

- name: Clone godep repo
  git:
    repo="https://github.com/tools/godep"
    dest="{{ go_path }}/src/github.com/tools/godep"
  become: true
  become_user: "{{ user }}"
  environment:
    GOPATH: "{{ go_path }}"

- name: Install godep
  shell: /usr/local/go/bin/go install .
  args:
    chdir: "{{ go_path }}/src/github.com/tools/godep"
  become: true
  become_user: "{{ user }}"
  environment:
    GOPATH: "{{ go_path }}"

- name: Get dependencies
  command: "{{ go_path }}/bin/godep get"
  args:
    chdir: "{{ service_dir }}/{{ item.name }}"
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ ansible_env.PATH }}:/home/{{ user }}/go/bin:/usr/local/go/bin"
  become: true
  become_user: "{{ user }}"
  with_items: "{{ services }}"
  tags:
    - update_custom_service_repo

- name: Config file
  copy:
    content="{{ item | to_nice_yaml }}"
    dest=/etc/{{ item.name }}.conf
    owner="{{ user }}"
    group="{{ group }}"
    mode=644
  become: true
  with_items: "{{ services }}"
  tags:
    - update_custom_service_repo

- name: Yaml config file
  lineinfile:
    dest=/etc/{{ item.name }}.conf
    line="---"
    insertbefore=BOF
    state=present
  with_items: "{{ services }}"
  become: true
  tags:
    - update_custom_service_repo

- name: Create go executable
  shell: /usr/local/go/bin/go install
  args:
    chdir: "{{ service_dir }}/{{ item.name }}"
  become: yes
  become_user: "{{ user }}"
  environment:
    GOPATH: "{{ go_path }}"
  with_items: "{{ services }}"
  tags:
    - update_custom_service_repo

- name: Kill existing daemons
  shell: "nohup start-stop-daemon --stop --signal TERM --retry 5 --quiet --oknodo --pidfile /var/run/{{ item.name }}.pid --exec /home/{{ user }}/go/bin/{{ item.name }} >> /tmp/service_{{ item.name }}.log 2>&1 &"
  become: yes
  with_items: "{{ services }}"
  tags:
    - update_services
    - update_custom_service_repo

- name: Start daemon
  shell: "nohup start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/{{ item.name }}.pid --exec /home/{{ user }}/go/bin/{{ item.name }} >> /tmp/service_{{ item.name }}.log 2>&1 &"
  become: yes
  with_items: "{{ services }}"
  tags:
    - update_services
    - update_custom_service_repo

  ###########
  # TESTING #
  ###########
# - name: Get ginkgo for testing
#   command: go get github.com/onsi/ginkgo/ginkgo
#   become: yes
#   become_user: "{{ user }}"

# - name: Get gomega for testing
#   command: go get github.com/onsi/gomega
#   become: yes
#   become_user: "{{ user }}"

# - name: Test gh-service
#   command: ginkgo -r
#   args:
#     chdir: "{{ service_dir }}"
#   become: yes
#   become_user: "{{ user }}"
